# Generated by Django 5.1.3 on 2024-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_name_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
