# Generated by Django 5.1.3 on 2024-12-02 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_quiz_points_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='number_of_tests_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_tests_done',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
