# Generated by Django 5.1.3 on 2024-12-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tests_done',
            field=models.ManyToManyField(blank=True, related_name='tests_done_by', to='api.test'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_tests_done',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
