# Generated by Django 5.1.3 on 2024-12-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_tests_done_alter_user_number_of_tests_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_tests_done',
        ),
    ]
