# Generated by Django 5.1.3 on 2024-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('jizzakh', 'Jizzax'), ('tashkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('fergana', 'Farg`ona'), ('andijan', 'Andijon'), ('namangan', 'Namangan'), ('bukhara', 'Buxoro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
