# Generated by Django 5.1.3 on 2024-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_age_user_city_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
