# Generated by Django 5.1.3 on 2024-12-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_test_number_of_questions_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('teacher', 'Ustoz'), ('student', 'O`quvchi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('jizzakh', 'Jizzax'), ('tashkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('fergana', 'Farg`ona'), ('andijan', 'Andijon'), ('namangan', 'Namangan'), ('bukhara', 'Buxoro'), ('termiz', 'Termiz'), ('navoi', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo')], max_length=20, null=True),
        ),
    ]
