# Generated by Django 5.1.3 on 2024-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_user_favorites_delete_favorite_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.IntegerField(choices=[(5, '5 sec'), (10, '10 sec'), (20, '20 sec'), (30, '30 sec'), (45, '45 sec'), (60, '60 sec'), (90, '90 sec'), (120, '120')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='timer_limit',
            field=models.IntegerField(choices=[(50, '50 pt'), (100, '100 pt'), (200, '200 pt'), (250, '250 pt'), (500, '500 pt'), (750, '750 pt'), (1000, '1000 pt'), (2000, '2000 pt')], default=50),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'multiple_choice'), ('true_false', 'true_false'), ('type_answer', 'type_answer'), ('poll', 'poll'), ('audio', 'audio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('in_queue', 'in_queue')], default='in_queue', max_length=20),
        ),
    ]
