# Generated by Django 5.1.3 on 2024-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_question_point_question_timer_limit_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
