# Generated by Django 5.1.3 on 2024-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_answer_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='question_image/'),
        ),
    ]
