# Generated by Django 5.1.3 on 2024-12-12 07:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=5),
        ),
    ]
