# Generated by Django 5.1.3 on 2024-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_test_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quiz_points',
            new_name='lifetime_quiz_points',
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
