# Generated by Django 5.1.3 on 2024-12-12 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_quiz_points_user_lifetime_quiz_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weekly_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0), blank=True, null=True, size=7),
        ),
    ]
