# Generated by Django 5.1.3 on 2024-12-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_user_weekly_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='weekly_points',
        ),
    ]
