# Generated by Django 5.1.3 on 2024-12-12 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_user_weekly_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=7),
        ),
    ]
