# Generated by Django 5.1.3 on 2024-12-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_answer_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='api.testparticipant'),
        ),
    ]
